name             'cheflab'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures cheflab'
long_description 'Installs/Configures cheflab'
version          '0.1.0'

depends 'chef-server12'
depends 'git'
depends 'java'
depends 'sudo'
depends 'jenkins'
depends 'chef-dk'
depends 'gitlab'
depends 'graphite'

depends 'python'
depends 'runit', '~> 1.0'
depends 'memcached'
depends 'build-essential'
depends 'yum-epel'
depends 'nginx'

suggests 'systemd'
suggests 'graphiti'
suggests 'delayed_evaluator'
